# Generated by Django 6.0.4 on 2026-04-19 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Submissão', 'verbose_name_plural': 'Submissões'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='areas_for_improvement',
            field=models.TextField(verbose_name='Pontos a Melhorar'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='constructive_feedback',
            field=models.TextField(verbose_name='Feedback Construtivo'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='key_strengths',
            field=models.TextField(verbose_name='Pontos Fortes'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(help_text='Enunciado completo da questão.', verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='question',
            name='rubric',
            field=models.TextField(help_text='Orientação do professor para a IA. O que se espera na resposta ideal.', verbose_name='Rubrica'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='answer_text',
            field=models.TextField(help_text='O texto escrito pelo aluno.', verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Nullable durante o MVP (sem autenticação).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
